---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: jhcook/osx-elcapitan-10.11

suites:
  - name: default
    run_list:
      - recipe[workstation-macos::default]
    attributes:
      workstation:
        packages: ['git', 'tig']
        applications: ['google-chrome', 'ccleaner']
        user: 'vagrant'
