---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: jhcook/osx-elcapitan-10.11

suites:
  - name: default
    run_list:
      - recipe[homebrew::default]
      - recipe[workstation-macos::default]
