name 'workstation-macos'
maintainer 'Brian Holtkamp'
maintainer_email 'brholtkamp@gmail.com'
license 'MIT'
description 'Installs/Configures workstation-macos'
long_description 'Installs/Configures workstation-macos'
version '0.1.0'
source_url 'https://github.com/brholtkamp/workstation-macos'
issues_url 'https://github.com/brholtkamp/workstation-macos/issues'

depends 'homebrew'
depends 'workstation-common'
