name 'workstation-macos'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workstation-macos'
long_description 'Installs/Configures workstation-macos'
version '0.1.0'
